### ISSUE TITLE
[Solved] Bug: Compile issue -- Update Azerothcore!

### ISSUE THREAD

**Issue by LuckyLuc96** [NathanHandley/mod-ah-bot#9]
### Current Behaviour

Azerothcore  is failing to compile with some recent changes, probably introduced in commit a9c5ae8152ff13356e6bcab6ceccf2dea440af72

It's related to Worldsession.h

> /home/luc/azerothcore/src/server/game/Server/WorldSession.h:1203:5: note: candidate constructor not viable: requires single argument 'right', but 12 arguments were provided

### Expected Behaviour

It should compile, and it isn't.

### Steps to reproduce the problem

pull latest changes. Recompile. Fail to recompile.

> mplementation-specific macros" [-W#warnings]
   49 | #    warning "<ciso646> is not a standard header since C++20, use <version> to detect implementation-specific macros"
      |      ^
/home/luc/azerothcore/modules/mod-ah-bot/src/AuctionHouseBot.cpp:758:18: error: no matching constructor for initialization of 'WorldSession'
  758 |     WorldSession _session(AHCharacters[botIndex].AccountID, std::move(accountName), 0, nullptr, SEC_PLAYER, sWorld->getIntConfig(CONFIG_EXPANSION), 0, LOCALE_enUS, 0, false, false, 0);
      |                  ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luc/azerothcore/src/server/game/Server/WorldSession.h:332:5: note: candidate constructor not viable: requires 11 arguments, but 12 were provided
  332 |     WorldSession(uint32 id, std::string&& name, std::shared_ptr<WorldSocket> sock, AccountTypes sec, uint8 expansion, time_t mute_time, LocaleConstant locale, uint32 recruiter, bool isARecruiter, bool skipQueue, uint32 TotalTime);
      |     ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luc/azerothcore/src/server/game/Server/WorldSession.h:1203:5: note: candidate constructor not viable: requires single argument 'right', but 12 arguments were provided
 1203 |     WorldSession(WorldSession const& right) = delete;
      |     ^            ~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

### AC rev. hash/commit

71b1ad1faafd

### Operating system

Fedora Linux

**Comment by LuckyLuc96** [comment]
I cheated and used some AI to point me the way. Removing the 0 from line 758 of AuctionHouseBot.cpp to change 

>  0, nullptr,

to 

> nullptr

fixed the issue on my side. But that looks like just a total reversion of that commit. What was the extra parameter supposed to do? I'm new to c++ so genuine question there.

**Comment by NathanHandley** [comment]
The issue would be the branch of Azerothcore you're using.  2 days ago, WorldSession.h added that additional parameter to the main branch in this change set: https://github.com/azerothcore/azerothcore-wotlk/commit/3f46e05d3691895b6b8a5b3832d17ecb1e210791.  

So you'll have to update the fork of AzerothCore to at least that change set.  If I change the code to take this parameter back out, then anyone on the newest version of AzerothCore will break.

I'm going to leave this bug open for a few days though so people see it, as I just closed one related to this.

**Comment by LuckyLuc96** [comment]
Ohhhh yes my azerothcore is about a week old. Thank you

> The issue would be the branch of Azerothcore you're using. 2 days ago, WorldSession.h added that additional parameter to the main branch in this change set: [azerothcore/azerothcore-wotlk@3f46e05](https://github.com/azerothcore/azerothcore-wotlk/commit/3f46e05d3691895b6b8a5b3832d17ecb1e210791).
> 
> So you'll have to update the fork of AzerothCore to at least that change set. If I change the code to take this parameter back out, then anyone on the newest version of AzerothCore will break.
> 
> I'm going to leave this bug open for a few days though so people see it, as I just closed one related to this.

**Comment by NathanHandley** [comment]
And to this question: "What was the extra parameter supposed to do?"

Kitzunu (developer on AzerothCore) has been working on moving an account flag to the world session code for performance and stability reasons.  It was related to this overall pull request which has a lot of details: https://github.com/azerothcore/azerothcore-wotlk/pull/22558
